"""empty message

Revision ID: 079728026c88
Revises: 
Create Date: 2024-05-13 16:57:27.967171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '079728026c88'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.alter_column('nameAdminPublique',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.alter_column('nameAdminPublique',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
