"""empty message

Revision ID: 251be00290fe
Revises: 
Create Date: 2024-05-10 21:10:08.084231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '251be00290fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('president_email', sa.String(length=100), nullable=False),
    sa.Column('instance_name', sa.String(length=100), nullable=False),
    sa.Column('nombre_conseille', sa.Integer(), nullable=True),
    sa.Column('gouvernement', sa.String(length=100), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=100), nullable=False),
    sa.Column('lastName', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('profile_image', sa.String(length=250), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('phoneNumber', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('instance_id', sa.Integer(), nullable=True),
    sa.Column('verification_code', sa.String(length=10), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['Role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ProgrammeVisite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('periode_debut', sa.DateTime(timezone=True), nullable=False),
    sa.Column('periode_fin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('criteres_evaluation', sa.String(length=500), nullable=False),
    sa.Column('lieu', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contacts_urgence', sa.String(length=200), nullable=True),
    sa.Column('documents_joints', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('conseiller_email', sa.String(length=100), nullable=False),
    sa.Column('admin_email', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Reunion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_reunion', sa.String(length=20), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('heure', sa.Time(), nullable=True),
    sa.Column('lieu', sa.String(length=100), nullable=True),
    sa.Column('ordre_du_jour', sa.Text(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('archived_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Resultat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('observations', sa.Text(), nullable=False),
    sa.Column('evaluations', sa.Text(), nullable=False),
    sa.Column('recommendations', sa.Text(), nullable=False),
    sa.Column('rapportPdf', sa.LargeBinary(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('programme_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['programme_id'], ['ProgrammeVisite.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('programme_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Resultat')
    op.drop_table('archived_users')
    op.drop_table('Reunion')
    op.drop_table('ProgrammeVisite')
    op.drop_table('Users')
    op.drop_table('instances')
    op.drop_table('Role')
    # ### end Alembic commands ###
