"""empty message

Revision ID: 492d1d31bc74
Revises: 
Create Date: 2024-06-17 19:00:20.983253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '492d1d31bc74'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ville', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('linkedin', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('lienFacebook', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('description_profil', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('description_profil')
        batch_op.drop_column('lienFacebook')
        batch_op.drop_column('linkedin')
        batch_op.drop_column('ville')

    # ### end Alembic commands ###
