"""empty message

Revision ID: d93ac1d5f065
Revises: 
Create Date: 2024-05-13 21:17:17.313602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd93ac1d5f065'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sent_email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sent_email',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('president_email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('instance_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], name='sent_email_instance_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='sent_email_pkey')
    )
    # ### end Alembic commands ###
